docs: Link to latest/edge docs instead of 2.0.0
I cloned the repo, clicked a link to the build guideline in
`CONTRIBUTING.md` and copied the "Build, install and bring up Harbor
without Notary" command:

    make install GOBUILDIMAGE=golang:1.12.5 COMPILETAG=compile_golangimage

Being unfamiliar with the Harbor project, I didn't realize that said
command was for building version 2.0.0 and that I had cloned a newer,
incompatible version (2.3.0), so I just ran it and was met by errors:

    […]
    # github.com/goharbor/harbor/src/lib/errors
    ../lib/errors/errors.go:26:7: undefined: errors.As
    ../lib/errors/errors.go:28:7: undefined: errors.Is
    note: module requires Go 1.15
    # github.com/hashicorp/go-multierror
    […]
    make: *** [Makefile:369: compile_core] Error 2

It took me a while to figure out what the problem was; then I replaced
`2.0.0` with `latest` in the URL and found this command instead:

    make install GOBUILDIMAGE=golang:1.13.8 COMPILETAG=compile_golangimage

_Et voilà_ – it worked!

I figured `latest` (which currently redirects to 2.2.0) would make the
most sense for end users and `edge` (which doesn't redirect) for
contributors.

Signed-off-by: Simon Alling <alling.simon@gmail.com>