missing syslog home directory breaks logrotate
Logrotate is run with sudo as the syslog user by cron.hourly
Without the syslog home directory, the job fails. Currently the following stderr is being thrown away by the cron script:
```
error: cannot open current directory: Permission denied
```

Fixes #15468

Signed-off-by: Christopher Jenkins <christj@gmail.com>