Fix error handling in test docker API
If image pull/push operations fail while running test cases, an
incorrect error message is printed instead of the actual error, e.g.:

Traceback (most recent call last):
  File "./tests/apitests/python/test_user_view_logs.py", line 82, in testUserViewLogs
    repo_name, tag = push_image_to_project(project_user_view_logs_name, harbor_server, admin_name, admin_password, "tomcat", "latest")
  File "/var/lib/harbor-test/tests/apitests/python/library/repository.py", line 34, in push_image_to_project
    _docker_api.docker_image_push(new_harbor_registry, new_tag, expected_error_message = expected_error_message)
  File "/var/lib/harbor-test/tests/apitests/python/library/docker_api.py", line 152, in docker_image_push
    raise Exception(r" Docker push image {} failed, error is [{}]".format (harbor_registry, message))
NameError: global name 'message' is not defined

Signed-off-by: Stefan Nica <snica@suse.com>