fix to yaml parse error causing Helm check failure
Error: YAML parse error on harbor/templates/registry/registry-ss.yaml: error converting YAML to JSON: yaml: line 63: did not find expected key